# Generated by Django 4.1.2 on 2022-10-26 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_badges_user_reward_points_community_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
