# Generated by Django 4.1.2 on 2022-10-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_challenge_comment_post_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.challenge'),
        ),
    ]
