# Generated by Django 4.1.2 on 2022-10-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_related_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_users',
            new_name='liked_users',
        ),
    ]
